companieshouse/insolvency-data-api

pom.xml, src/itest/java/uk/gov/companieshouse/insolvency/data/repository/RepositoryITest.java, src/main/java/uk/gov/companieshouse/insolvency/data/config/ApplicationConfig.java, src/main/java/uk/gov/companieshouse/insolvency/data/converter/CompanyInsolvencyReadConverter.java, src/main/java/uk/gov/companieshouse/insolvency/data/converter/EnumConverters.java, src/main/java/uk/gov/companieshouse/insolvency/data/model/InsolvencyDocument.java, src/main/java/uk/gov/companieshouse/insolvency/data/serialization/LocalDateDeSerializer.java, src/main/java/uk/gov/companieshouse/insolvency/data/serialization/LocalDateSerializer.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImpl.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/NoopTransactionServiceImpl.java, src/main/resources/application.yml
https://companieshouse.atlassian.net/browse/DSND-653
Update insolvency-data-api service
=> DSND-653: Update insolvency-data-api service

pom.xml, routes.yaml, src/itest/java/uk/gov/companieshouse/insolvency/data/steps/InsolvencySteps.java, src/main/java/uk/gov/companieshouse/insolvency/data/api/InsolvencyApiService.java, src/main/java/uk/gov/companieshouse/insolvency/data/controller/InsolvencyController.java, src/test/java/uk/gov/companieshouse/insolvency/data/controller/InsolvencyControllerTest.java
Changes to the routes and related endpoint adding beta in front
=> Changes to the routes and related endpoint adding beta in front

pom.xml, src/itest/resources/json/input/case_type_compulsory_liquidation.json, src/itest/resources/json/input/case_type_receivership.json, src/itest/resources/json/output/case_type_compulsory_liquidation_output.json, src/itest/resources/json/output/case_type_receivership_output.json, src/itest/resources/json/output/retrieve_by_company_number.json
DSND-729 Insolvency Data API - Changes after Case Number definition from integer to String
=> DSND-729 Insolvency Data API - Changes after Case Number definition

src/main/java/uk/gov/companieshouse/insolvency/data/api/InsolvencyApiService.java, src/main/java/uk/gov/companieshouse/insolvency/data/config/ExceptionHandlerConfig.java, src/main/java/uk/gov/companieshouse/insolvency/data/exceptions/BadRequestException.java, src/main/java/uk/gov/companieshouse/insolvency/data/exceptions/MethodNotAllowedException.java, src/main/java/uk/gov/companieshouse/insolvency/data/exceptions/ServiceUnavailableException.java, src/main/java/uk/gov/companieshouse/insolvency/data/serialization/LocalDateDeSerializer.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImpl.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/NoopTransactionServiceImpl.java, src/test/java/uk/gov/companieshouse/insolvency/data/api/InsolvencyApiClientServiceTest.java, src/test/java/uk/gov/companieshouse/insolvency/data/controller/InsolvencyControllerTest.java, src/test/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImplTest.java
Ticket: https://companieshouse.atlassian.net/browse/DSND-456
Implemented new response codes for insolvency PUT endpoint (400, 405, 500, 503)
=> DSND-456: Return non 2xx response codes for PUT endpoint

src/main/java/uk/gov/companieshouse/insolvency/data/config/ExceptionHandlerConfig.java
Hotfix to include different exception handler for invalid date format
Removed correlationId from message logs
=> Hotfix DSND-456: DateTime exception handler for date deserialization

Makefile, pom.xml
Address issue when Integration Test fail but Build Success in CI - Integration Testing Component
=> Address issue when Integration Test fail but Build Success in CI

src/itest/java/uk/gov/companieshouse/insolvency/data/steps/InsolvencySteps.java, src/itest/resources/features/company-insolvency-delete.feature, src/main/java/uk/gov/companieshouse/insolvency/data/controller/InsolvencyController.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImpl.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/NoopTransactionServiceImpl.java, src/test/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImplTest.java
Deleting insolvency, returns 200 if deleted successfully, otherwise 404 if the insolvency doesn't exist, integration tests updated.
=> Deleting insolvency implemented, with integration tests

src/itest/java/uk/gov/companieshouse/insolvency/data/steps/InsolvencySteps.java, src/itest/resources/features/company-insolvency-delete.feature, src/itest/resources/features/company-insolvency-error-retry.feature, src/itest/resources/features/company-insolvency-happy-path.feature, src/main/java/uk/gov/companieshouse/insolvency/data/api/InsolvencyApiService.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImpl.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/NoopTransactionServiceImpl.java, src/test/java/uk/gov/companieshouse/insolvency/data/api/InsolvencyApiClientServiceTest.java, src/test/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImplTest.java
Calls ChsKafkaApi with "deleted" event when deleting an insolvency
=> Calling CHS kafka api when deleting insolvency, updated unit tests and integration tests

src/main/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImpl.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/NoopTransactionServiceImpl.java
DSND-839 Address issue when updated_at is stored wrongly in the DB
=> DSND-839 Address issue when updated_at is stored wrongly in the DB

src/main/java/uk/gov/companieshouse/insolvency/data/api/InsolvencyApiService.java
Steps 
Send the insolvency request for the insolvency 
Error occurs in the insolvency-data-api
Resolves: https://companieshouse.atlassian.net/browse/DSND-876
=> Kafka Api Event Type now sends 'changed/deleted' instead of 'CHANGED/DELETED'

src/main/resources/application.yml
Resolves: https://companieshouse.atlassian.net/browse/DSND-878
=> DSND-878-Not returning nulls

src/main/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImpl.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/NoopTransactionServiceImpl.java
DSND-889 - Address the issue with status.
=> DSND-889 - Address the issue with status.

pom.xml
DSND-895 - Updated private SDK version in POM after moratorium was added
=> DSND-895 - Updated private SDK version in POM after moratorium was added

src/main/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImpl.java
DSND-895 - changes to test the pipeline
=> DSND-895 - changes to test the pipeline

src/main/java/uk/gov/companieshouse/insolvency/data/model/InsolvencyDocument.java, src/main/resources/application.yml
Externalise collection name in application.yml file
=> Externalise collection name in application.yml file

src/main/java/uk/gov/companieshouse/insolvency/data/converter/EnumConverters.java, src/main/java/uk/gov/companieshouse/insolvency/data/converter/OffsetDateTimeReadConverter.java, src/main/java/uk/gov/companieshouse/insolvency/data/serialization/LocalDateDeSerializer.java, src/main/java/uk/gov/companieshouse/insolvency/data/serialization/LocalDateSerializer.java, src/main/java/uk/gov/companieshouse/insolvency/data/util/DateTimeFormatter.java, src/test/java/uk/gov/companieshouse/insolvency/data/serialization/LocalDateDeSerializerTest.java, src/test/java/uk/gov/companieshouse/insolvency/data/serialization/LocalDateSerializerTest.java, src/test/java/uk/gov/companieshouse/insolvency/data/util/DateTimeFormatterTest.java
Serialization and converter improvements
=> Serialization and converter improvements

src/main/java/uk/gov/companieshouse/insolvency/data/config/ExceptionHandlerConfig.java, src/test/java/uk/gov/companieshouse/insolvency/data/config/ExceptionHandlerConfigTest.java
Exception Handling Improvements
=> Exception Handling Improvements

.gitignore, pom.xml
This pr updates the private sdk version to include change to make practitioner postcode optional.
**Required for:**
DSND-1195
=> make practitioner postcode optional

src/itest/resources/features/company-insolvency-delete.feature, src/itest/resources/features/company-insolvency-happy-path.feature, src/main/java/uk/gov/companieshouse/insolvency/data/config/ExceptionHandlerConfig.java, src/main/java/uk/gov/companieshouse/insolvency/data/exceptions/DocumentNotFoundException.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImpl.java, src/test/java/uk/gov/companieshouse/insolvency/data/config/ExceptionHandlerConfigTest.java, src/test/java/uk/gov/companieshouse/insolvency/data/controller/InsolvencyControllerTest.java, src/test/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImplTest.java
Revert all not found back to gone
=> All not found status reverted back to gone

src/itest/resources/features/company-insolvency-delete.feature, src/itest/resources/features/company-insolvency-happy-path.feature, src/main/java/uk/gov/companieshouse/insolvency/data/config/ExceptionHandlerConfig.java, src/main/java/uk/gov/companieshouse/insolvency/data/exceptions/DocumentGoneException.java, src/main/java/uk/gov/companieshouse/insolvency/data/exceptions/DocumentNotFoundException.java, src/main/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImpl.java, src/test/java/uk/gov/companieshouse/insolvency/data/config/ExceptionHandlerConfigTest.java, src/test/java/uk/gov/companieshouse/insolvency/data/controller/InsolvencyControllerTest.java, src/test/java/uk/gov/companieshouse/insolvency/data/service/InsolvencyServiceImplTest.java
Insolvency - return a 404 response when a resource is not found
=> All 410 status code changed to 404

src/itest/java/uk/gov/companieshouse/insolvency/data/steps/InsolvencySteps.java, src/main/java/uk/gov/companieshouse/insolvency/data/auth/EricTokenAuthenticationFilter.java, src/main/java/uk/gov/companieshouse/insolvency/data/controller/InsolvencyController.java, src/test/java/uk/gov/companieshouse/insolvency/data/auth/EricTokenAuthenticationFilterTest.java, src/test/java/uk/gov/companieshouse/insolvency/data/controller/InsolvencyControllerTest.java
* Authorise OAUTH2 requests only if they are GET requests
* Authorise KEY requests only if they have internal app privileges or if they are GET requests
[DSND-1540](https://companieshouse.atlassian.net/browse/DSND-1540)
[DSND-1540]: https://companieshouse.atlassian.net/browse/DSND-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-1540 Implement authorisation check for internal app privileges

Makefile, pom.xml, src/itest/resources/features/heath-check-api.feature, src/main/resources/application.yml, suppress.xml
- Replace Companies House Parent version to 2.1.6
- Upgrade Spring Boot Version to at least 3.3.0
- Make sure the Jib plugin docker images are correct
- Implement the new vulnerability suppression method
Jira: [JU-523](https://companieshouse.atlassian.net/browse/JU-523)
[JU-523]: https://companieshouse.atlassian.net/browse/JU-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> insolvency-data-api tech debt

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars, terraform/groups/ecs-service/variables.tf
[DSND-3054](https://companieshouse.atlassian.net/browse/DSND-3054)
[DSND-3054]: https://companieshouse.atlassian.net/browse/DSND-3054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-3054: Increase task resources

src/main/java/uk/gov/companieshouse/insolvency/data/api/InsolvencyApiService.java, src/main/java/uk/gov/companieshouse/insolvency/data/util/DateTimeFormatter.java, src/test/java/uk/gov/companieshouse/insolvency/data/util/DateTimeFormatterTest.java
This PR reduces the precision of the published at time to seconds.
[BI-13959](https://companieshouse.atlassian.net/browse/BI-13959)
[BI-13959]: https://companieshouse.atlassian.net/browse/BI-13959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-13959: Change published at precision to seconds

Makefile
[DSND-2953](https://companieshouse.atlassian.net/browse/DSND-2953)
[DSND-2953]: https://companieshouse.atlassian.net/browse/DSND-2953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2953: Remove routes yml from makefile command

pom.xml, src/main/java/uk/gov/companieshouse/insolvency/data/api/InsolvencyApiService.java, src/main/java/uk/gov/companieshouse/insolvency/data/config/ApplicationConfig.java, src/main/java/uk/gov/companieshouse/insolvency/data/exceptions/SerDesException.java, src/test/java/uk/gov/companieshouse/insolvency/data/api/InsolvencyApiClientServiceTest.java
* Serialise/deserialise data before passing to changed resource
* Add object mapper config
* Add SerDesException and handling for mapper error cases
* Update parent pom version and internal dependencies
* Update spring, test containers, cucumber and maven plugin versions
* Address testcontainers vulnerability
Resolves [DSND-3094](https://companieshouse.atlassian.net/browse/DSND-3094)
[DSND-3094]: https://companieshouse.atlassian.net/browse/DSND-3094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-3094: Remove null fields from stream events

pom.xml
https://companieshouse.atlassian.net/browse/ASM-502
Add config for latest Sonar to POM
and use sonar-maven-plugin.version from parent pom
=> ASM-502 Add latest Sonar config to POM
